# Generated by Django 5.1.1 on 2024-09-15 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('reservations', models.IntegerField(default=0)),
                ('movie_id', models.IntegerField()),
                ('seats', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('seats', models.IntegerField(default=100)),
                ('available_seats', models.IntegerField(default=100)),
                ('reservations', models.IntegerField(default=0)),
                ('photo', models.CharField(default='https://st2.depositphotos.com/1105977/9877/i/450/depositphotos_98775856-stock-photo-retro-film-production-accessories-still.jpg', max_length=255)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reservedSeats', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservations_code', models.CharField(blank=True, editable=False, max_length=4, unique=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reservations', to='tickets.guest')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reservations', to='tickets.movie')),
            ],
        ),
    ]
