# Generated by Django 5.1.1 on 2024-09-17 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_reservation_guest_alter_reservation_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='reservations',
            new_name='reservations',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='reservations',
            new_name='reservations',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_set', to='tickets.guest'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_set', to='tickets.movie'),
        ),
    ]
