# Generated by Django 5.1.1 on 2024-10-13 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_guest_movie_id_movie_actors_movie_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='time',
        ),
        migrations.AddField(
            model_name='guest',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='fhd_image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='show_times',
            field=models.JSONField(default=dict),
        ),
    ]
