# Generated by Django 5.1.1 on 2024-10-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_remove_movie_date_remove_movie_time_guest_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='show_times',
            field=models.JSONField(default=list),
        ),
    ]
