# Generated by Django 5.1.1 on 2024-10-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_movie_show_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='available_seats',
            field=models.IntegerField(default=models.IntegerField(default=100)),
        ),
    ]
